# Generated by Django 4.0.5 on 2022-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bills_products_users_tokens_bills_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expiry_date',
            field=models.DateTimeField(max_length=20),
        ),
    ]
